name: Publish
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Pull repo
      - uses: actions/checkout@v2
      # Install bun
      - uses: oven-sh/setup-bun@v2
      # Run tests
      # TODO: Add tests
      # Build
      - run: bun build
      # Publish
      - run: bun publish
        env:
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org/_authToken=${{ secrets.NPM_TOKEN }}
